
package com.webservice.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NciicServicesPortType", targetNamespace = "http://ws.webservice.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NciicServicesPortType {


    /**
     * 
     * @param inLicense
     * @param inConditions
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://ws.webservice.com")
    @RequestWrapper(localName = "nciicDiscern", targetNamespace = "http://ws.webservice.com", className = "com.webservice.ws.NciicDiscern")
    @ResponseWrapper(localName = "nciicDiscernResponse", targetNamespace = "http://ws.webservice.com", className = "com.webservice.ws.NciicDiscernResponse")
    public String nciicDiscern(
        @WebParam(name = "inLicense", targetNamespace = "http://ws.webservice.com")
        String inLicense,
        @WebParam(name = "inConditions", targetNamespace = "http://ws.webservice.com")
        String inConditions);

    /**
     * 
     * @param inLicense
     * @param id
     * @return
     *     returns com.webservice.ws.FileObjectSetPhone
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://ws.webservice.com")
    @RequestWrapper(localName = "nciicCheckGetPhone", targetNamespace = "http://ws.webservice.com", className = "com.webservice.ws.NciicCheckGetPhone")
    @ResponseWrapper(localName = "nciicCheckGetPhoneResponse", targetNamespace = "http://ws.webservice.com", className = "com.webservice.ws.NciicCheckGetPhoneResponse")
    public FileObjectSetPhone nciicCheckGetPhone(
        @WebParam(name = "inLicense", targetNamespace = "http://ws.webservice.com")
        String inLicense,
        @WebParam(name = "id", targetNamespace = "http://ws.webservice.com")
        String id);

    /**
     * 
     * @param inLicense
     * @param inConditions
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://ws.webservice.com")
    @RequestWrapper(localName = "nciicCheckChina", targetNamespace = "http://ws.webservice.com", className = "com.webservice.ws.NciicCheckChina")
    @ResponseWrapper(localName = "nciicCheckChinaResponse", targetNamespace = "http://ws.webservice.com", className = "com.webservice.ws.NciicCheckChinaResponse")
    public String nciicCheckChina(
        @WebParam(name = "inLicense", targetNamespace = "http://ws.webservice.com")
        String inLicense,
        @WebParam(name = "inConditions", targetNamespace = "http://ws.webservice.com")
        String inConditions);

    /**
     * 
     * @param inLicense
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://ws.webservice.com")
    @RequestWrapper(localName = "nciicGetCondition", targetNamespace = "http://ws.webservice.com", className = "com.webservice.ws.NciicGetCondition")
    @ResponseWrapper(localName = "nciicGetConditionResponse", targetNamespace = "http://ws.webservice.com", className = "com.webservice.ws.NciicGetConditionResponse")
    public String nciicGetCondition(
        @WebParam(name = "inLicense", targetNamespace = "http://ws.webservice.com")
        String inLicense);

    /**
     * 
     * @param inLicense
     * @param inConditions
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://ws.webservice.com")
    @RequestWrapper(localName = "nciicExactSearch", targetNamespace = "http://ws.webservice.com", className = "com.webservice.ws.NciicExactSearch")
    @ResponseWrapper(localName = "nciicExactSearchResponse", targetNamespace = "http://ws.webservice.com", className = "com.webservice.ws.NciicExactSearchResponse")
    public String nciicExactSearch(
        @WebParam(name = "inLicense", targetNamespace = "http://ws.webservice.com")
        String inLicense,
        @WebParam(name = "inConditions", targetNamespace = "http://ws.webservice.com")
        String inConditions);

    /**
     * 
     * @param inLicense
     * @param inConditions
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://ws.webservice.com")
    @RequestWrapper(localName = "nciicCourt", targetNamespace = "http://ws.webservice.com", className = "com.webservice.ws.NciicCourt")
    @ResponseWrapper(localName = "nciicCourtResponse", targetNamespace = "http://ws.webservice.com", className = "com.webservice.ws.NciicCourtResponse")
    public String nciicCourt(
        @WebParam(name = "inLicense", targetNamespace = "http://ws.webservice.com")
        String inLicense,
        @WebParam(name = "inConditions", targetNamespace = "http://ws.webservice.com")
        String inConditions);

    /**
     * 
     * @param inLicense
     * @param inConditions
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://ws.webservice.com")
    @RequestWrapper(localName = "nciicFmxxEntry", targetNamespace = "http://ws.webservice.com", className = "com.webservice.ws.NciicFmxxEntry")
    @ResponseWrapper(localName = "nciicFmxxEntryResponse", targetNamespace = "http://ws.webservice.com", className = "com.webservice.ws.NciicFmxxEntryResponse")
    public String nciicFmxxEntry(
        @WebParam(name = "inLicense", targetNamespace = "http://ws.webservice.com")
        String inLicense,
        @WebParam(name = "inConditions", targetNamespace = "http://ws.webservice.com")
        String inConditions);

    /**
     * 
     * @param inLicense
     * @param inConditions
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://ws.webservice.com")
    @RequestWrapper(localName = "nciicCheck", targetNamespace = "http://ws.webservice.com", className = "com.webservice.ws.NciicCheck")
    @ResponseWrapper(localName = "nciicCheckResponse", targetNamespace = "http://ws.webservice.com", className = "com.webservice.ws.NciicCheckResponse")
    public String nciicCheck(
        @WebParam(name = "inLicense", targetNamespace = "http://ws.webservice.com")
        String inLicense,
        @WebParam(name = "inConditions", targetNamespace = "http://ws.webservice.com")
        String inConditions);

    /**
     * 
     * @param inLicense
     * @param inConditions
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://ws.webservice.com")
    @RequestWrapper(localName = "nciicCombineSearch", targetNamespace = "http://ws.webservice.com", className = "com.webservice.ws.NciicCombineSearch")
    @ResponseWrapper(localName = "nciicCombineSearchResponse", targetNamespace = "http://ws.webservice.com", className = "com.webservice.ws.NciicCombineSearchResponse")
    public String nciicCombineSearch(
        @WebParam(name = "inLicense", targetNamespace = "http://ws.webservice.com")
        String inLicense,
        @WebParam(name = "inConditions", targetNamespace = "http://ws.webservice.com")
        String inConditions);

    /**
     * 
     * @param inLicense
     * @param inConditions
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://ws.webservice.com")
    @RequestWrapper(localName = "nciicCheckMobile", targetNamespace = "http://ws.webservice.com", className = "com.webservice.ws.NciicCheckMobile")
    @ResponseWrapper(localName = "nciicCheckMobileResponse", targetNamespace = "http://ws.webservice.com", className = "com.webservice.ws.NciicCheckMobileResponse")
    public String nciicCheckMobile(
        @WebParam(name = "inLicense", targetNamespace = "http://ws.webservice.com")
        String inLicense,
        @WebParam(name = "inConditions", targetNamespace = "http://ws.webservice.com")
        String inConditions);

    /**
     * 
     * @param fileObject
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://ws.webservice.com")
    @RequestWrapper(localName = "nciicCheckFile", targetNamespace = "http://ws.webservice.com", className = "com.webservice.ws.NciicCheckFile")
    @ResponseWrapper(localName = "nciicCheckFileResponse", targetNamespace = "http://ws.webservice.com", className = "com.webservice.ws.NciicCheckFileResponse")
    public String nciicCheckFile(
        @WebParam(name = "fileObject", targetNamespace = "http://ws.webservice.com")
        FileObject fileObject) throws InterruptedException;

    /**
     * 
     * @param inLicense
     * @param inConditions
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://ws.webservice.com")
    @RequestWrapper(localName = "nciicCheckHotel", targetNamespace = "http://ws.webservice.com", className = "com.webservice.ws.NciicCheckHotel")
    @ResponseWrapper(localName = "nciicCheckHotelResponse", targetNamespace = "http://ws.webservice.com", className = "com.webservice.ws.NciicCheckHotelResponse")
    public String nciicCheckHotel(
        @WebParam(name = "inLicense", targetNamespace = "http://ws.webservice.com")
        String inLicense,
        @WebParam(name = "inConditions", targetNamespace = "http://ws.webservice.com")
        String inConditions);

    /**
     * 
     * @param inLicense
     * @param inConditions
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://ws.webservice.com")
    @RequestWrapper(localName = "nciicKyxxEntry", targetNamespace = "http://ws.webservice.com", className = "com.webservice.ws.NciicKyxxEntry")
    @ResponseWrapper(localName = "nciicKyxxEntryResponse", targetNamespace = "http://ws.webservice.com", className = "com.webservice.ws.NciicKyxxEntryResponse")
    public String nciicKyxxEntry(
        @WebParam(name = "inLicense", targetNamespace = "http://ws.webservice.com")
        String inLicense,
        @WebParam(name = "inConditions", targetNamespace = "http://ws.webservice.com")
        String inConditions);

    /**
     * 
     * @param inKey
     * @param inLicense
     * @param inConditions
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://ws.webservice.com")
    @RequestWrapper(localName = "nciicCompareScan", targetNamespace = "http://ws.webservice.com", className = "com.webservice.ws.NciicCompareScan")
    @ResponseWrapper(localName = "nciicCompareScanResponse", targetNamespace = "http://ws.webservice.com", className = "com.webservice.ws.NciicCompareScanResponse")
    public String nciicCompareScan(
        @WebParam(name = "inLicense", targetNamespace = "http://ws.webservice.com")
        String inLicense,
        @WebParam(name = "inConditions", targetNamespace = "http://ws.webservice.com")
        String inConditions,
        @WebParam(name = "inKey", targetNamespace = "http://ws.webservice.com")
        String inKey);

    /**
     * 
     * @param inLicense
     * @param inConditions
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://ws.webservice.com")
    @RequestWrapper(localName = "nciicBirthplaceCompare", targetNamespace = "http://ws.webservice.com", className = "com.webservice.ws.NciicBirthplaceCompare")
    @ResponseWrapper(localName = "nciicBirthplaceCompareResponse", targetNamespace = "http://ws.webservice.com", className = "com.webservice.ws.NciicBirthplaceCompareResponse")
    public String nciicBirthplaceCompare(
        @WebParam(name = "inLicense", targetNamespace = "http://ws.webservice.com")
        String inLicense,
        @WebParam(name = "inConditions", targetNamespace = "http://ws.webservice.com")
        String inConditions);

    /**
     * 
     * @param inLicense
     * @param id
     * @return
     *     returns com.webservice.ws.FileObject
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://ws.webservice.com")
    @RequestWrapper(localName = "nciicGetFile", targetNamespace = "http://ws.webservice.com", className = "com.webservice.ws.NciicGetFile")
    @ResponseWrapper(localName = "nciicGetFileResponse", targetNamespace = "http://ws.webservice.com", className = "com.webservice.ws.NciicGetFileResponse")
    public FileObject nciicGetFile(
        @WebParam(name = "inLicense", targetNamespace = "http://ws.webservice.com")
        String inLicense,
        @WebParam(name = "id", targetNamespace = "http://ws.webservice.com")
        String id);

    /**
     * 
     * @param inLicense
     * @param inConditions
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://ws.webservice.com")
    @RequestWrapper(localName = "nciicAddrExactSearch", targetNamespace = "http://ws.webservice.com", className = "com.webservice.ws.NciicAddrExactSearch")
    @ResponseWrapper(localName = "nciicAddrExactSearchResponse", targetNamespace = "http://ws.webservice.com", className = "com.webservice.ws.NciicAddrExactSearchResponse")
    public String nciicAddrExactSearch(
        @WebParam(name = "inLicense", targetNamespace = "http://ws.webservice.com")
        String inLicense,
        @WebParam(name = "inConditions", targetNamespace = "http://ws.webservice.com")
        String inConditions);

    /**
     * 
     * @param fileObject
     * @return
     *     returns com.webservice.ws.FileObjectSetPhone
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://ws.webservice.com")
    @RequestWrapper(localName = "nciicCheckSetPhone", targetNamespace = "http://ws.webservice.com", className = "com.webservice.ws.NciicCheckSetPhone")
    @ResponseWrapper(localName = "nciicCheckSetPhoneResponse", targetNamespace = "http://ws.webservice.com", className = "com.webservice.ws.NciicCheckSetPhoneResponse")
    public FileObjectSetPhone nciicCheckSetPhone(
        @WebParam(name = "fileObject", targetNamespace = "http://ws.webservice.com")
        FileObjectSetPhone fileObject);

    /**
     * 
     * @param inLicense
     * @param inConditions
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://ws.webservice.com")
    @RequestWrapper(localName = "nciicCompare", targetNamespace = "http://ws.webservice.com", className = "com.webservice.ws.NciicCompare")
    @ResponseWrapper(localName = "nciicCompareResponse", targetNamespace = "http://ws.webservice.com", className = "com.webservice.ws.NciicCompareResponse")
    public String nciicCompare(
        @WebParam(name = "inLicense", targetNamespace = "http://ws.webservice.com")
        String inLicense,
        @WebParam(name = "inConditions", targetNamespace = "http://ws.webservice.com")
        String inConditions);

    /**
     * 
     * @param inLicense
     * @param inConditions
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://ws.webservice.com")
    @RequestWrapper(localName = "nciicDateCollection", targetNamespace = "http://ws.webservice.com", className = "com.webservice.ws.NciicDateCollection")
    @ResponseWrapper(localName = "nciicDateCollectionResponse", targetNamespace = "http://ws.webservice.com", className = "com.webservice.ws.NciicDateCollectionResponse")
    public String nciicDateCollection(
        @WebParam(name = "inLicense", targetNamespace = "http://ws.webservice.com")
        String inLicense,
        @WebParam(name = "inConditions", targetNamespace = "http://ws.webservice.com")
        String inConditions);

    /**
     * 
     * @param inKey
     * @param inLicense
     * @param inConditions
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://ws.webservice.com")
    @RequestWrapper(localName = "nciicCheckScan", targetNamespace = "http://ws.webservice.com", className = "com.webservice.ws.NciicCheckScan")
    @ResponseWrapper(localName = "nciicCheckScanResponse", targetNamespace = "http://ws.webservice.com", className = "com.webservice.ws.NciicCheckScanResponse")
    public String nciicCheckScan(
        @WebParam(name = "inLicense", targetNamespace = "http://ws.webservice.com")
        String inLicense,
        @WebParam(name = "inConditions", targetNamespace = "http://ws.webservice.com")
        String inConditions,
        @WebParam(name = "inKey", targetNamespace = "http://ws.webservice.com")
        String inKey);

}
