
package com.webservice.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NciicServicesPortTypeImpl", targetNamespace = "http://ws.webservice.com", wsdlLocation = "file:/E:/workspace/web-service/src/main/resources/NciicServices.wsdl")
public class NciicServicesPortTypeImpl
    extends Service
{

    private final static URL NCIICSERVICESPORTTYPEIMPL_WSDL_LOCATION;
    private final static WebServiceException NCIICSERVICESPORTTYPEIMPL_EXCEPTION;
    private final static QName NCIICSERVICESPORTTYPEIMPL_QNAME = new QName("http://ws.webservice.com", "NciicServicesPortTypeImpl");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/E:/workspace/web-service/src/main/resources/NciicServices.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NCIICSERVICESPORTTYPEIMPL_WSDL_LOCATION = url;
        NCIICSERVICESPORTTYPEIMPL_EXCEPTION = e;
    }

    public NciicServicesPortTypeImpl() {
        super(__getWsdlLocation(), NCIICSERVICESPORTTYPEIMPL_QNAME);
    }

    public NciicServicesPortTypeImpl(WebServiceFeature... features) {
        super(__getWsdlLocation(), NCIICSERVICESPORTTYPEIMPL_QNAME, features);
    }

    public NciicServicesPortTypeImpl(URL wsdlLocation) {
        super(wsdlLocation, NCIICSERVICESPORTTYPEIMPL_QNAME);
    }

    public NciicServicesPortTypeImpl(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NCIICSERVICESPORTTYPEIMPL_QNAME, features);
    }

    public NciicServicesPortTypeImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NciicServicesPortTypeImpl(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NciicServicesPortType
     */
    @WebEndpoint(name = "NciicServicesHttpPort")
    public NciicServicesPortType getNciicServicesHttpPort() {
        return super.getPort(new QName("http://ws.webservice.com", "NciicServicesHttpPort"), NciicServicesPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NciicServicesPortType
     */
    @WebEndpoint(name = "NciicServicesHttpPort")
    public NciicServicesPortType getNciicServicesHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.webservice.com", "NciicServicesHttpPort"), NciicServicesPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NCIICSERVICESPORTTYPEIMPL_EXCEPTION!= null) {
            throw NCIICSERVICESPORTTYPEIMPL_EXCEPTION;
        }
        return NCIICSERVICESPORTTYPEIMPL_WSDL_LOCATION;
    }

}
